### ISSUE TITLE
Bold text is not rendered as bold

### ISSUE THREAD

**Issue by rafaeleyng** [codeheaven-io/codeheaven.io#15]
I've used Markdown's `**`, the `<strong>` tag was generated, it was styled (both by user agent's default and by our custom CSS) as bold, but didn't rendered as bold. I've checked the Google Fonts URL, it downloads the weight 900. Setting `font-weight: 900;` for the `<strong>` didn't work. I must be missing something.

I would really like to use some bold text.

**Comment by marlonbernardes** [comment]
Yeah, it is, in fact, really difficult to see what is bold:

![image](https://cloud.githubusercontent.com/assets/2975955/8848399/706c6584-310d-11e5-9553-f898d375dd26.png)

I'll take a look at it.

**Comment by marlonbernardes** [comment]
@rafaeleyng Done. You can merge #16 whenever you want!
