### ISSUE TITLE
Reduce the font size

### ISSUE THREAD

**Issue by rafaeleyng** [codeheaven-io/codeheaven.io#18]
I think the font size for the regular text, links, code is pretty big. T. I suggest it to be around 0.9em.

**Comment by marlonbernardes** [comment]
Wow! I only saw this issue now, 17 days after you opened it! Is it still a valid issue? Does it still needs to be fixed? It seems to be in a appropriate size here. Please check it again and report here if you still find it to be big! :)

**Comment by rafaeleyng** [comment]
I think it is bigger than it should. Most blogs that I see use a slightly smaller font, like:
- [HTML5 Rocks](http://updates.html5rocks.com/2015/06/checkout-faster-with-autofill)
- [Giant Robots Smashing into Other Giant Robots](https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template)
- [CSS-Tricks](https://css-tricks.com/)

This is totally opinion-based and might be closed as well. I just think that the big font makes to few text to be visible in the screen at a time.
