### ISSUE TITLE
Rename the project and update README.md

### ISSUE THREAD

**Issue by rafaeleyng** [codeheaven-io/codeheaven.io#2]
I suggest to rename the project from `codeheaven.io` to `codeheaven`. Is kind o messy to have a folder with a dot in the name (I know, everyone could clone the project changing the name, but that's not usually expected), specially in Windows (not my case, but anyway).

The "update README.md" part is about renaming the project also in the installation steps.

**Comment by marlonbernardes** [comment]
I think that codeheaven.io reflects clearly that this repo refers to the website. It' not uncommon to see repos in github named after a website domain, so I suggest we leave things as they are, IMO.

**Comment by rafaeleyng** [comment]
I think the name codeheaven.io is better than codeheaven, yes.
I'm basically bothered about what would happen in Windows when a user create a folder with a dot in the name, because I really don't know.
But yes, is a minor concern.

**Comment by marlonbernardes** [comment]
I don't see why it wouldn't work on Windows. I see dots on folder names all the time: maven dependencies, installed programs, System folders, ruby gems, etc. I don't think we should worry about that.

**Comment by rafaeleyng** [comment]
I thought that Windows would interpret it as a file with .io extension and wouldn't open the folder on double click.
Closing.
