### ISSUE TITLE
Prefix CSS classes

### ISSUE THREAD

**Issue by rafaeleyng** [codeheaven-io/codeheaven.io#3]
I had a nice experience with using CSS classes prefixes, so I would like us to use the prefix `ch-` in our own CSS classes.

Do you agree?

**Comment by marlonbernardes** [comment]
I don't particularly like that. Thats one of the reasons why I dont like pure.css - it leaks the framework name on every class we have to use. Besides that, I dont think its really semantic and we would have a hard time copying this styles to a new, unrelated, project (we all do that from time to time, right?)

**Comment by rafaeleyng** [comment]
Suppose we are, somewhere - I don't mean in this project, using Bootstrap, Perfect Scrollbar and our own custom classes in some component of our app (I will be inventing the prefixes and class names, so bear with me).

A world without prefixes:

``` html
<div class="pull-right">
  <div class="container">
    <div class="item-list">
      ...
    </div>
  </div>
</div>
```

A world with prefixes:

``` html
<div class="bs-pull-right">
  <div class="ps-container">
    <div class="ch-item-list">
      ...
    </div>
  </div>
</div>
```

> it leaks the framework name on every class we have to use

I don't see that as a problem. We can differentiate Pure's classes from our own classes just by looking at them.

> I dont think its really semantic

`container` vs `ps-container`, I don't see a loss of semantics. Maybe a increase of semantics: "oh, thats the container that PS needs to create the scrollbar" (not arguing that that's how PS operates). What I mean is: you don't seem to loose semantics by adding a prefix.

> we would have a hard time copying this styles to a new, unrelated, project

If you want to copy this component **without** prefixes:
- you will copy the 3 divs
- you will start looking for the 3 classes used. You don't have a clue where they live, so the easiest way is to open it in your browser (start the server? is your environment installed?) and inspect the elements. 
- eventually you find your classes in some CSS files and have to decide from which files you can copy stuff (I don't think you'll be just copying a class from PS, you would probably have to import the whole plugin).

If you want to copy this component **with** prefixes:
- you will look at the component in the HTML code (no need to run the project, probably) and conclude "ok, this component uses framework/plugin classes besides my own", and then decide what you would do about it (if you want to copy Bootstrap and PS classes at all etc).

If you mean copying a whole CSS file, you have only to do a "Find" by `.ch-` and "Replace" by another prefix of by nothing.

If you've tried using CSS classes prefixes and had a bad time, I would like to hear about it. If you haven't tried it yet, I would suggest you to try it to see if you like it.

**Comment by dwayhs** [comment]
I personally don't like using the prefixes.
I'm not saying it's a bad approach. If it works well for you, it's ok.

But, for me, the semantics are way more important. And it is not about not losing the semantic, it's about the correct semantic.

I like the foundation approach, clean and very semantic:

``` html
<a href="#whatever" class="large primary button">Call for action</a>
```

**Comment by marlonbernardes** [comment]
I haven't tried a lot of things which I don't like!
The reason (even thought it's not well articulated) I don't like it is the same why I don't like adding types preffixes to my js code (aka Ungarian Notation). It's more of a personal preference.

Since I think that we should not follow one's preferences (like mine), I encourage this type of discussion. I just say that we should define, together, a style guide and follow it.

**Comment by dwayhs** [comment]
I agree.

My contribution to the discussion:
https://medium.com/@fat/mediums-css-is-actually-pretty-fucking-good-b8e2a6c78b06

I really like the medium style guide.

**Comment by rafaeleyng** [comment]
No prefixes then. Closing.

**Comment by rafaeleyng** [comment]
About the style guide, I like the idea of following a style guide. What I don't like is to create and maintain a style guide, because my little experience tells me that small organizations just won't maintain it and probably won't follow it fully if not enforced by a build tool that checks it.

So I think is better for us to follow a nice style guide (like medium, airbnb, whatever) that incurring the overhead of maintaining it.
